language: android
android:
  components:
    - build-tools-28.0.0
    - android-28
    - add-on
    - extra

    before_install:
      - chmod +x gradlew  # 改变gradlew的访问权限

    script:              # 执行:下面的命令
      - ./gradlew assembleRelease
